image: docker:latest

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - ssh-keyscan -t rsa 192.168.35.102 >> ~/.ssh/known_hosts
  - echo "$CAIRO_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

services:
  - name: docker:dind
    alias: dockerhost

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

variables:
    CONTAINER_LATEST_IMAGE: $CI_REGISTRY_IMAGE:latest
    DOCKER_HOST: tcp://dockerhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

build:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - docker build --pull . --cache-from $CONTAINER_LATEST_IMAGE -t $CONTAINER_LATEST_IMAGE --build-arg WP_API_DOMAIN=$WP_API_DOMAIN --build-arg BASIC_AUTH_USERNAME=$BASIC_AUTH_USERNAME --build-arg BASIC_AUTH_PASSWORD=$BASIC_AUTH_PASSWORD
    - docker push $CONTAINER_LATEST_IMAGE
    - echo "Compile complete."
  only:
    - master

deploy:      # This job runs in the deploy stage.
  stage: deploy
  script:
    - echo "Deploying application..."
    - ssh deploy@192.168.35.102 "docker-compose -f /opt/win-gg/docker-compose.yml pull frontend && docker-compose -f /opt/win-gg/docker-compose.yml up -d"
    - echo "Application successfully deployed."
  only:
    - master
  when: manual